consumes:
- application/json
definitions:
  klikform_src_interfaces_v1_schemas_auths.AuthBodySchema:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  klikform_src_interfaces_v1_schemas_auths.AuthResponseSchema:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  klikform_src_interfaces_v1_schemas_masters.UserBodySchema:
    properties:
      address:
        type: string
      email:
        type: string
      fullname:
        type: string
      password:
        type: string
      phone:
        type: string
      role_id:
        type: string
      status:
        type: string
    required:
    - email
    - fullname
    - password
    - role_id
    - status
    type: object
  klikform_src_interfaces_v1_schemas_masters.UserResponseSchema:
    properties:
      address:
        type: string
      created_at:
        type: string
      email:
        type: string
      fullname:
        type: string
      id:
        type: string
      phone:
        type: string
      status:
        type: string
    type: object
  klikform_src_interfaces_v1_schemas_masters.WorkspaceBodySchema:
    properties:
      descriptions:
        type: string
      remark:
        type: string
      status:
        type: string
      title:
        type: string
    required:
    - descriptions
    - status
    - title
    type: object
  klikform_src_interfaces_v1_schemas_masters.WorkspaceResponseSchema:
    properties:
      descriptions:
        type: string
      id:
        type: string
      remark:
        type: string
      status:
        type: string
      title:
        type: string
    type: object
  schemas.ResponseSchema:
    properties:
      data: {}
      error: {}
      message:
        type: string
    type: object
  schemas.WelcomeResponseSchema:
    properties:
      about:
        type: string
      version:
        type: string
    type: object
info:
  contact: {}
  description: Klikform API Service
  title: KlikForm API
  version: "1.0"
paths:
  /auth:
    post:
      consumes:
      - application/json
      description: Get access token by login
      parameters:
      - description: Auth body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/klikform_src_interfaces_v1_schemas_auths.AuthBodySchema'
      responses:
        "200":
          description: Successful response
          schema:
            allOf:
            - $ref: '#/definitions/schemas.ResponseSchema'
            - properties:
                data:
                  $ref: '#/definitions/klikform_src_interfaces_v1_schemas_auths.AuthResponseSchema'
              type: object
        "400":
          description: Failure response
          schema:
            $ref: '#/definitions/schemas.ResponseSchema'
      summary: Authentication
      tags:
      - Auth
  /roles:
    get:
      description: List of role available
      parameters:
      - description: Page number
        in: query
        name: page
        required: true
        type: integer
      - description: Items per page
        in: query
        name: limit
        required: true
        type: integer
      - description: Search keywords
        in: query
        name: keywords
        type: string
      responses:
        "200":
          description: Successful response
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Failure response
          schema:
            additionalProperties: true
            type: object
      summary: Role List
      tags:
      - Master - Roles
  /users:
    get:
      description: List of user available
      parameters:
      - description: Page number
        in: query
        name: page
        required: true
        type: integer
      - description: Items per page
        in: query
        name: limit
        required: true
        type: integer
      - description: Search keywords
        in: query
        name: keywords
        type: string
      responses:
        "200":
          description: Successful response
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Failure response
          schema:
            additionalProperties: true
            type: object
      summary: User List
      tags:
      - Master - Users
    post:
      consumes:
      - application/json
      description: Create new user
      parameters:
      - description: User body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/klikform_src_interfaces_v1_schemas_masters.UserBodySchema'
      responses:
        "200":
          description: Successful response
          schema:
            allOf:
            - $ref: '#/definitions/schemas.ResponseSchema'
            - properties:
                data:
                  $ref: '#/definitions/klikform_src_interfaces_v1_schemas_masters.UserResponseSchema'
              type: object
        "400":
          description: Failure response
          schema:
            $ref: '#/definitions/schemas.ResponseSchema'
      summary: User Create
      tags:
      - Master - Users
  /users/{id}:
    delete:
      description: Delete existing user
      parameters:
      - description: ID of user
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: Successful response
        "400":
          description: Failure response
          schema:
            additionalProperties: true
            type: object
      summary: User Delete
      tags:
      - Master - Users
    get:
      description: Detail of user
      parameters:
      - description: ID of user
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: Successful response
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Failure response
          schema:
            additionalProperties: true
            type: object
      summary: User Detail
      tags:
      - Master - Users
    put:
      consumes:
      - application/json
      description: Update existing user
      parameters:
      - description: ID of user
        in: path
        name: id
        required: true
        type: string
      - description: User body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/klikform_src_interfaces_v1_schemas_masters.UserBodySchema'
      responses:
        "204":
          description: Successful response
        "400":
          description: Failure response
          schema:
            $ref: '#/definitions/schemas.ResponseSchema'
      summary: User Update
      tags:
      - Master - Users
  /welcome:
    get:
      description: Welcome entry point to test API run
      responses:
        "200":
          description: Successful response
          schema:
            allOf:
            - $ref: '#/definitions/schemas.ResponseSchema'
            - properties:
                data:
                  $ref: '#/definitions/schemas.WelcomeResponseSchema'
              type: object
      summary: Welcome point
      tags:
      - Welcome
  /workspaces:
    get:
      description: List of workspace available
      parameters:
      - description: Page number
        in: query
        name: page
        required: true
        type: integer
      - description: Items per page
        in: query
        name: limit
        required: true
        type: integer
      - description: Search keywords
        in: query
        name: keywords
        type: string
      responses:
        "200":
          description: Successful response
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Failure response
          schema:
            additionalProperties: true
            type: object
      summary: Workspace List
      tags:
      - Master - Workspaces
    post:
      consumes:
      - application/json
      description: Create new workspace
      parameters:
      - description: Workspace body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/klikform_src_interfaces_v1_schemas_masters.WorkspaceBodySchema'
      responses:
        "200":
          description: Successful response
          schema:
            allOf:
            - $ref: '#/definitions/schemas.ResponseSchema'
            - properties:
                data:
                  $ref: '#/definitions/klikform_src_interfaces_v1_schemas_masters.WorkspaceResponseSchema'
              type: object
        "400":
          description: Failure response
          schema:
            $ref: '#/definitions/schemas.ResponseSchema'
      summary: Workspace Create
      tags:
      - Master - Workspaces
  /workspaces/{id}:
    get:
      description: Detail of workspace
      parameters:
      - description: ID of workspace
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: Successful response
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Failure response
          schema:
            additionalProperties: true
            type: object
      summary: Workspace Detail
      tags:
      - Master - Workspaces
produces:
- application/json
security:
- BearerAuth: []
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
